language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
install:
  - yarn